---
deployment:
  tasks:
    - export DEPLOYPATH=/home/najaedco/lammas.dev/projects/library/
    - /bin/cp -R app/base $DEPLOYPATH/app/
    - /bin/cp -R app/controllers $DEPLOYPATH/app/
    - /bin/cp -R app/helpers $DEPLOYPATH/app/
    - /bin/cp -R app/models $DEPLOYPATH/app/
    - /bin/cp -R app/views $DEPLOYPATH/app/
    - /bin/cp app/.htaccess $DEPLOYPATH/app/.htaccess
    - /bin/cp app/main.php $DEPLOYPATH/app/main.php
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH