---
deployment:
  tasks:
    - export DEPLOYPATH=/home/najaedco/lammas.dev/projects/library/
    - /bin/cp -RT app/base "$DEPLOYPATH/app/base/"
    - /bin/cp -RT app/controllers "$DEPLOYPATH/app/controllers/"
    - /bin/cp -RT app/helpers "$DEPLOYPATH/app/helpers/"
    - /bin/cp -RT app/models "$DEPLOYPATH/app/models/"
    - /bin/cp -RT app/views "$DEPLOYPATH/app/views/"
    - /bin/cp app/.htaccess "$DEPLOYPATH/app/.htaccess"
    - /bin/cp app/main.php "$DEPLOYPATH/app/main.php"
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH